apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    # access: proxy
    # url: clickhouse:8123
    # database: default
    # user: default
    jsonData:
      protocol: http
      #secure: false
      defaultDatabase: BigDataAnalytics
      port: 8123
      host: clickhouse
      username: default
      #tlsSkipVerify: true
    secureJsonData:
      password: clickhouse
    editable: true